version: '3'
services: 
  dev: 
    image: node:lts-alpine3.16
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: npm run dev
    ports: 
      - "5000:8080"

volumes:
  nodemodules:
    external: true

  # backend-api:
  #   build: ./
  #   command: npm run dev
  #   ports:
  #   - "5000:8080"
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  
